
//list of historical facts
const quotes = ["Augustus Caesar was the wealthiest man to ever live in history.",
"Alexander the Great was buried alive… accidentally.",
"The world’s most successful pirate in history was a lady.",
"In the Ancient Olympics, athletes performed naked.",
"Julius Caesar was stabbed 23 times.",
"The Colosseum was originally clad entirely in marble.",
"The Colosseum was named because it was next to a statue called the Colossus.",
"Rasputin survived being poisoned and being shot.",
"There were female Gladiators.",
"The Vikings were the first people to discover America.",
"The Luftwaffe had a master interrogator whose tactic was being as nice as possible.",
"In Ancient Asia, death by elephant was a popular form of execution.",
"The UK government collected postcards as intelligence for the D-Day landings.",
"When Marcus Crassus died, molten gold was poured down his throat.",
"Germany uncovers 2,000 tons of unexploded bombs every year",
"In Ancient Greece, wearing skirts was manly.",
"A singing birthday card has more computer power in it than the entire Allied Army of WWII.",
"In 1386, a pig was executed in France.",
"Cleopatra’s reign was closer to the moon landings than the Great Pyramid being built.",
"Shrapnel is named after its inventor.",
"Since 1945, all British tanks are equipped with tea-making facilities.",
"During World War I, the French built a “fake Paris”.",
"The Eastern Roman Empire’s weapon called Greek Fire was used in ship-mounted flamethrowers.",
"An ancient text called the Voynich Manuscript still baffles scientists.",
"A Japanese fighter pilot once dropped wreaths over the ocean to commemorate the dead from both sides.",
"4% of the Normandy beaches are made up of shrapnel from the D-Day Landings.",
"The saying “fly off the handle” originates from the 1800s.",
"“Fox Tossing” was once a popular sport.",
"Turkeys were once worshiped as Gods.",
"Captain Morgan was a real guy.",
"Genghis Khan was tolerant of all religions.",
"Thomas Edison didn’t invent most of the stuff he patented.",
"Albert Einstein turned down the presidency of Israel.",
"Roman Emperor Caligula made one of his favorite horses a senator.",
"Pope Gregory IX declared war on cats.",
"The Leaning Tower of Pisa was never straight.",
"During the Great Depression, people made clothes out of food sacks.",
"Lord Byron kept a bear in his college dorm.",
"Iceland has the world’s oldest parliament in history.",
"Since the end of WWI, over 1,000 people have died from leftover unexploded bombs.",
"46 BC was 445 days long and is the longest year in human history",
"100 million years ago, the Sahara Desert was inhabited by galloping crocodiles.",
"During the Victorian period, it was normal to photograph relatives after they died.",
"One man survived both the atomic bombing of Hiroshima and then later Nagasaki. Tsutomu Yamaguchi",
"The shortest war in history lasted 38 minutes.",
"Before the 19th Century, dentures were made from dead soldiers’ teeth.",
"Tug of War used to be an Olympic sport.",
"People were buried alive so often, that bells were attached to their coffins.",
"The term “saved by the bell” does not originate from people being buried alive. But from Boxing",
"George Washington didn’t have wooden teeth.",
"During a Roman Triumph, soldiers sang lewd songs about their commander to amuse the crowds.",
"Ancient Egyptian Pharaohs used their slaves as flycatchers.",
"In Ancient Rome, urine was used as a mouthwash.",
"In the Victorian era, men with mustaches used special cups.",
"The earliest ever lottery was during the Chinese Han Dynasty between 205 – 187 BC.",
"The Roman lottery’s prizes were known and were damn savage at times.",
"Spartans were so rich that nobody had to work.",
"Spartan women-owned most of the land and wealth in Sparta.",
"The University of Oxford is older than the Aztec Empire.",
"The World War II army of the US is the biggest army in history.",
"Only 6 people died in the Great Fire of London.",
"Count Dracula was inspired by a real person.",
"The most prolific female serial killer was a Hungarian Countess.",
"For 12 years during the French Revolutionary Period, France had a whole new calendar.",
"Genghis Khan created one of the first international postal systems.",
"During WWII, the British & Soviets launched a joint invasion of neutral Iran.",
"One in 200 men are direct descendants of Genghis Khan.",
"Russia ran out of vodka celebrating the end of World War II",
"There were “dance marathons” during the Great Depression.",
"The Circus Maximum in Rome is still the largest capacity sports arena ever built",
"The fastest surgeon ever ended up causing a 300% mortality rate.",
"Adolf Hitler’s nephew fought against the Nazis in World War II.",
"Charles Darwin invented his own wheeled office chair.",
"The first official Medals of Honor were awarded during the American Civil War.",
];

const randomQuote = (array) => {
    const randomIndex = Math.floor(Math.random() * array.length);
    console.log(array[randomIndex]);
}

randomQuote(quotes);
